### ISSUE TITLE
Set up Framework and Placeholder

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/railgun-shielder#1]
- [x] Set up next.js with necessary configuration
- [x] Add a simple README with a 1 sentence project description and a brief section on developer setup/usage
- [x] Add a blank placeholder page with some text
- [x] It should be possible to build the app to static page—there should be no server side rendering requirements

**Comment by alexkeating** [comment]
Leveraged rainbow kits template generation tool which goes a little beyond these criteria. Docs to the template generation tool can be found below

https://github.com/rainbow-me/rainbowkit#quick-start

**Comment by apbendi** [comment]
closed by #5
