### ISSUE TITLE
Add token lists for Ethereum, BSC, Polygon, Arbitrum, Goerli

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/railgun-shielder#11]
Per spec:

> Show searchable list of default ERC20 tokens.
> Support for Ethereum, BSC, Polygon, Arbitrum, Goerli.

Integrate into app!

Will we use coingecko token lists for each network?

**Comment by mds1** [comment]
> Will we use coingecko token lists for each network?

The coingecko list is absolutely massive with ~5k tokens, most of which are probably junk. I'd suggest a smaller, more curated list. I'd suggest just using the [Uniswap default list](https://tokenlists.org/token-list?url=https://gateway.ipfs.io/ipns/tokens.uniswap.org), which is a single list that covers mainnet, polygon, arbitrum, and goerli (well, it has two goerli tokens, which probably is ok and we can augment that manually with our mintable testnet tokens if needed). 

For BSC I found [these lists](https://github.com/pancakeswap/token-list/tree/main/lists) from pancakeswap. We can probably use one of those (top 100 maybe?) unless someone has a preference for another source

**Comment by mds1** [comment]
Consider storing the token list in some global state/context, fetching the JSON file on app load, and on wallet connect we fetch user balances for all tokens in that file with a multicall. That way when a user fills out the form we can validate entered amounts with no delay
