### ISSUE TITLE
UI: "How to shield"

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/railgun-shielder#15]
From reqs: 

> “How to shield” and “What happens to shielded funds” should be obvious to first-time visitors.

Let's include a "how to shield" section with appropriate copy. My first thought is that this belongs as a top level component that's visible just beside or below the form, but open to other ideas. Design-wise, should be considered together with #16

**Comment by mds1** [comment]
For umbra we have a tutorial component directly below the main actions you can choose from on the home page. Not saying this is the best design, but just noting it as some inspiration / an option

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/17163988/210563006-e2f996f3-b9e2-47ad-8a90-4b34996fbf03.png">
