### ISSUE TITLE
Transaction: "Review transaction" modal

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/railgun-shielder#17]
From reqs:

> Show a “Review transaction” view after selecting the amount(s) and token(s) to shield, which highlights shielding fee.

UI inspo from uniswap

**Comment by mds1** [comment]
> UI inspo from uniswap

Screenshot for reference 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/17163988/210563167-dd0d1a7f-72b7-4b6a-8f40-e04b99771f08.png">
