### ISSUE TITLE
Transaction: Toast on tx success/failure

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/railgun-shielder#23]
From reqs:

> Toast UI: success or failure toast with link to etherscan / bscscan / polygon / etc

**Comment by alexkeating** [comment]
Example code from the collectible

- https://github.com/ScopeLift/umbra-collectible/blob/master/apps/frontend/utils/alerts.ts
- https://github.com/ScopeLift/umbra-collectible/blob/d5e0131c1b188b59f4fd5b5f219b29e061375ab8/apps/frontend/hooks/useClaim.tsx#L58
