### ISSUE TITLE
URL og metadata

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/railgun-shielder#24]
from reqs:

> Metadata for URL links on Twitter, Telegram, Discord

**Comment by mds1** [comment]
As part of this issue let's also fix the favicon 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/17163988/215100691-40070b50-cb87-4155-a6e4-131eb69fe61b.png">

**Comment by alexkeating** [comment]
Do we have logos yet? And will the social information be for Railgun or specific to the shielder?

**Comment by apbendi** [comment]
Update title to say "Token Shielder" instead of "Railgun Shielder" @mds1
