### ISSUE TITLE
Add and Configure Wallet Connection

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/railgun-shielder#3]
- [x] Add standard wallet connection components from Rainbow, onboard.js, or similar
- [x] Should support, at a minimum browser extensions and Walletconnect
- [x] Should support/require supported networks (Ethereum, BSC, Polygon, Aribtrum, Goerli)
- [x] Should be placed in the top right hand corner and follow typical dApp UX patterns

**Comment by alexkeating** [comment]
Rainbows template generation knocked a few of these out.

**Comment by mds1** [comment]
@wildmolasses Closed by https://github.com/ScopeLift/railgun-shielder/pull/5? All items listed above are complete now

**Comment by mds1** [comment]
Just tested walletconnect and it worked (didn't try sending a tx of course), so closing this issue
