### ISSUE TITLE
Investigate whether pancakeswaps token list is in the initial bundle

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/railgun-shielder#38]
If it is in the initial bundle we can move the file to IPFS and reference it from there. If it isn't in the initial bundle we can leave it as is

**Comment by mds1** [comment]
Currently getting lots of token list fetch errors
![image](https://user-images.githubusercontent.com/17163988/214094682-12fe602f-425a-47f4-8d57-1bbc411e7770.png)

Fetching from IPFS will likely be bad UX unfortunately, so we should either (1) find an alternative URL for any IPFS lists, or (2) just store all token lists locally in JSON files

**Comment by wildmolasses** [comment]
closing in favor of #43
