### ISSUE TITLE
Potentially store token list statically

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/railgun-shielder#43]
We should revisit how we store the token list once we understand which tokens we need to support. We may want to switch to storing the tokens statically.

**Comment by wildmolasses** [comment]
another consideration here is that we don't support rebase tokens, and want to check token lists against a static blacklist. if we fetch hosted token lists dynamically, there is a risk that a rebase token will have been added, but that our blacklist has not yet been adjusted.

**Comment by wildmolasses** [comment]
See @mds1 comment on ipfs problems

https://github.com/ScopeLift/railgun-shielder/issues/38#issuecomment-1400636356
