### ISSUE TITLE
Cannot update component while rendering different component

### ISSUE THREAD

**Issue by mds1** [ScopeLift/railgun-shielder#63]
I'm seeing this error in the console 
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/17163988/214171953-52a7e7f7-2145-4481-875b-02df7daa04b0.png">

_Originally posted by @mds1 in https://github.com/ScopeLift/railgun-shielder/pull/59#discussion_r1084658493_

**Comment by alexkeating** [comment]
Did the review transaction modal fix this?

**Comment by mds1** [comment]
Seems that way, I haven't come across this again yet. I'll close this for now and re-open if I see it again
